// AUTO-GENERATED by Makefile - DO NOT EDIT
#include "../external/gui.h"

extern void tmnt_maker_open(void);
extern void turtlenotes_open(void);

void gui_init(void) {
    gui_register_auto_app("tmnt_maker", "tmnt_maker", tmnt_maker_open);
    gui_register_auto_app("turtlenotes", "turtlenotes", turtlenotes_open);
}
