// AUTO-GENERATED by Makefile - DO NOT EDIT
#include "../external/gui.h"

extern void minipack_open(void);
extern void sound_studio_open(void);
extern void tam_parser_open(void);
extern void tmnt_bot_open(void);
extern void tmnt_maker_open(void);
extern void turtlenotes_open(void);

void gui_init(void) {
    gui_register_auto_app("minipack", "minipack", minipack_open);
    gui_register_auto_app("sound_studio", "sound_studio", sound_studio_open);
    gui_register_auto_app("tam_parser", "tam_parser", tam_parser_open);
    gui_register_auto_app("tmnt_bot", "tmnt_bot", tmnt_bot_open);
    gui_register_auto_app("tmnt_maker", "tmnt_maker", tmnt_maker_open);
    gui_register_auto_app("turtlenotes", "turtlenotes", turtlenotes_open);
}
