#include "tam_parser.h"
#include "../../external/gui.h"
#include "../../fs/tmnt_fs.h"
#include "../../system/string.h"
#include "../../system/memory.h"

extern uint32_t* fb;
extern uint32_t fb_width, fb_height, fb_pitch;

static char tam_input[4096];
static int tam_input_pos = 0;
static char status_msg[256] = "TAM App Creator - Write TAM code and press Ctrl+S to build";
static char tam_filepath[128] = "/user/myapp.tam";

typedef struct {
    char keyword[32];
    char replacement[256];
} tam_command_t;

static tam_command_t tam_commands[] = {
    {"#app", "void"},
    {"#draw", "static void draw_content"},
    {"#click", "static void handle_click"},
    {"#key", "static void handle_key"},
    {"#icon", "// icon:"},
    {"#window", "// window:"},
    {"fill_rect", "gui_fb_fill_rect"},
    {"draw_rect", "gui_fb_draw_rect"},
    {"text", "gui_fb_draw_text"},
    {"putpixel", "gui_fb_putpixel"},
    {"if", "if"},
    {"for", "for"},
    {"while", "while"},
    {"end", "}"},
    {"begin", "{"},
};

static int tam_cmd_count = 15;

// Manual string prefix compare
static int str_starts(const char* str, const char* prefix) {
    while(*prefix) {
        if(*str != *prefix) return 0;
        str++;
        prefix++;
    }
    return 1;
}

// Convert TAM code to C code
static void tam_to_c(const char* tam, char* c_out, int max_out, const char* appname) {
    (void)max_out;
    c_out[0] = 0;
    
    // Add headers
    strcat(c_out, "// Generated by TAM Parser\n#include \"");
    strcat(c_out, appname);
    strcat(c_out, ".h\"\n#include \"../../external/gui.h\"\n\n");
    
    int has_draw = 0, has_click = 0, has_key = 0;
    char draw_code[2048] = "";
    char click_code[1024] = "";
    char key_code[1024] = "";
    char current_section[32] = "";
    
    // Parse lines
    char line[256];
    const char* p = tam;
    
    while(*p) {
        // Get one line
        int li = 0;
        while(*p && *p != '\n' && li < 255) {
            line[li++] = *p++;
        }
        line[li] = 0;
        if(*p == '\n') p++;
        
        // Skip empty lines
        if(line[0] == 0) continue;
        
        // Check for section headers
        if(line[0] == '#') {
            if(str_starts(line, "#draw")) {
                strcpy(current_section, "draw");
                has_draw = 1;
                continue;
            } else if(str_starts(line, "#click")) {
                strcpy(current_section, "click");
                has_click = 1;
                continue;
            } else if(str_starts(line, "#key")) {
                strcpy(current_section, "key");
                has_key = 1;
                continue;
            } else if(str_starts(line, "#app")) {
                strcpy(current_section, "");
                continue;
            }
            // Other # lines are comments
            continue;
        }
        
        // Translate line
        char translated[256] = "";
        char* token = line;
        while(*token == ' ' || *token == '\t') {
            int l = strlen(translated);
            translated[l] = *token;
            translated[l+1] = 0;
            token++;
        }
        
        // Check for TAM commands
        int matched = 0;
        for(int i = 0; i < tam_cmd_count; i++) {
            int kwlen = strlen(tam_commands[i].keyword);
            if(str_starts(token, tam_commands[i].keyword)) {
                strcat(translated, tam_commands[i].replacement);
                strcat(translated, token + kwlen);
                strcat(translated, ";\n");
                matched = 1;
                break;
            }
        }
        
        if(!matched) {
            strcat(translated, token);
            strcat(translated, ";\n");
        }
        
        // Add to appropriate section
        if(strcmp(current_section, "draw") == 0) {
            strcat(draw_code, "    ");
            strcat(draw_code, translated);
        } else if(strcmp(current_section, "click") == 0) {
            strcat(click_code, "    ");
            strcat(click_code, translated);
        } else if(strcmp(current_section, "key") == 0) {
            strcat(key_code, "    ");
            strcat(key_code, translated);
        }
    }
    
    // Build draw function
    if(has_draw) {
        strcat(c_out, "static void draw_content(int wx, int wy, int ww, int wh) {\n");
        strcat(c_out, draw_code);
        strcat(c_out, "}\n\n");
    }
    
    // Build click function
    if(has_click) {
        strcat(c_out, "static void handle_click(int mx, int my) {\n");
        strcat(c_out, click_code);
        strcat(c_out, "}\n\n");
    }
    
    // Build key function
    if(has_key) {
        strcat(c_out, "static void handle_key(char key) {\n");
        strcat(c_out, key_code);
        strcat(c_out, "}\n\n");
    }
    
    // Build open function
    strcat(c_out, "void ");
    strcat(c_out, appname);
    strcat(c_out, "_open(void) {\n");
    strcat(c_out, "    gui_run_auto_app(\"");
    strcat(c_out, appname);
    strcat(c_out, "\", 100, 50, 600, 400, ");
    strcat(c_out, has_draw ? "draw_content" : "0");
    strcat(c_out, ", ");
    strcat(c_out, has_click ? "handle_click" : "0");
    strcat(c_out, ", ");
    strcat(c_out, has_key ? "handle_key" : "0");
    strcat(c_out, ");\n}\n");
}

// Build the app from TAM code
static int tam_build(const char* appname) {
    if(!appname || !appname[0]) {
        strcpy(status_msg, "Error: No app name. Use #app MyAppName at top of TAM code");
        return -1;
    }
    
    // Create app directory
    char appdir[128] = "/apps/";
    strcat(appdir, appname);
    fs_create_dir(appdir);
    
    // Generate C code
    char c_code[4096];
    tam_to_c(tam_input, c_code, 4096, appname);
    
    // Write .c file
    char cpath[128];
    strcpy(cpath, appdir);
    strcat(cpath, "/");
    strcat(cpath, appname);
    strcat(cpath, ".c");
    fs_write_file(cpath, (uint8_t*)c_code, strlen(c_code));
    
    // Write .h file
    char hpath[128];
    strcpy(hpath, appdir);
    strcat(hpath, "/");
    strcat(hpath, appname);
    strcat(hpath, ".h");
    
    char header[512];
    strcpy(header, "// ");
    strcat(header, appname);
    strcat(header, " - TAM Generated\n#ifndef ");
    for(int i = 0; appname[i]; i++) {
        char c = appname[i];
        if(c >= 'a' && c <= 'z') c -= 32;
        int l = strlen(header);
        header[l] = c;
        header[l+1] = 0;
    }
    strcat(header, "_H\n#define ");
    for(int i = 0; appname[i]; i++) {
        char c = appname[i];
        if(c >= 'a' && c <= 'z') c -= 32;
        int l = strlen(header);
        header[l] = c;
        header[l+1] = 0;
    }
    strcat(header, "_H\n\nvoid ");
    strcat(header, appname);
    strcat(header, "_open(void);\n\n#endif\n");
    fs_write_file(hpath, (uint8_t*)header, strlen(header));
    
    strcpy(status_msg, "App '");
    strcat(status_msg, appname);
    strcat(status_msg, "' built! Rebuild ISO to use.");
    return 0;
}

// Draw function
static void tam_draw(int wx, int wy, int ww, int wh) {
    // Title
    for(int dy = 0; dy < 28; dy++) {
        uint8_t g = 20 + dy * 4;
        uint32_t color = (0x00 << 16) | (g << 8) | 0x00;
        for(int dx = 4; dx < ww - 4; dx++) {
            gui_fb_putpixel(wx + dx, wy + 30 + dy, color);
        }
    }
    gui_fb_draw_rect(wx + 4, wy + 30, ww - 8, 28, 0x00FF00);
    gui_fb_draw_text(wx + (ww - 180) / 2, wy + 36, "🛠️ TAM APP CREATOR 🛠️", 0x00FF00, 0x0A2A0A);
    
    // Code editor area
    int edit_x = wx + 10, edit_y = wy + 65, edit_w = ww - 20, edit_h = wh - 170;
    gui_fb_fill_rect(edit_x - 1, edit_y - 1, edit_w + 2, edit_h + 2, 0x003300);
    gui_fb_fill_rect(edit_x, edit_y, edit_w, edit_h, 0x0A0A0A);
    
    // Display TAM code
    int ypos = edit_y + 5;
    const char* p = tam_input;
    char line[256];
    while(*p && ypos < edit_y + edit_h - 16) {
        int li = 0;
        while(*p && *p != '\n' && li < 255) line[li++] = *p++;
        line[li] = 0;
        if(*p == '\n') p++;
        
        uint32_t fg = 0x00CC00;
        if(line[0] == '#') fg = 0xFFFF00;
        
        gui_fb_draw_text(edit_x + 5, ypos, line, fg, 0x0A0A0A);
        ypos += 16;
    }
    
    // Status bar
    int status_y = wy + wh - 90;
    gui_fb_fill_rect(wx + 10, status_y, ww - 20, 22, 0x0A1A0A);
    gui_fb_draw_rect(wx + 10, status_y, ww - 20, 22, 0x00CC00);
    gui_fb_draw_text(wx + 15, status_y + 3, status_msg, 0xFFFF00, 0x0A1A0A);
    
    // Help text
    gui_fb_draw_text(wx + 15, wy + wh - 60, "Commands: #app Name | #draw | #click | #key | fill_rect | text | putpixel", 0x666666, 0x0A1A0A);
    gui_fb_draw_text(wx + 15, wy + wh - 44, "Ctrl+S: Build App | Ctrl+L: Load .tam file | Ctrl+N: New | Ctrl+H: Help", 0x666666, 0x0A1A0A);
    
    // Filepath display
    gui_fb_draw_text(wx + 15, wy + wh - 28, "File: ", 0x888888, 0x0A1A0A);
    gui_fb_draw_text(wx + 55, wy + wh - 28, tam_filepath, 0x00AA00, 0x0A1A0A);
}

static void tam_click(int mx, int my) {
    (void)mx;
    (void)my;
}

static void tam_key(char key) {
    if(key == 19) { // Ctrl+S
        // Extract app name from TAM code
        char appname[32] = "tamapp";
        const char* p = tam_input;
        while(*p == ' ' || *p == '\n') p++;
        if(str_starts(p, "#app ")) {
            p += 5;
            int n = 0;
            while(*p && *p != '\n' && *p != ' ' && n < 30) {
                appname[n++] = *p++;
            }
            appname[n] = 0;
        }
        tam_build(appname);
        return;
    }
    
    if(key == 12) { // Ctrl+L
        tam_input[0] = 0;
        tam_input_pos = 0;
        if(fs_file_exists(tam_filepath)) {
            uint32_t sz = fs_get_file_size(tam_filepath);
            if(sz > 0 && sz < 4000) {
                fs_read_file(tam_filepath, (uint8_t*)tam_input, sz);
                tam_input[sz] = 0;
                tam_input_pos = sz;
            }
        }
        strcpy(status_msg, "Loaded from file");
        return;
    }
    
    if(key == 14) { // Ctrl+N
        tam_input[0] = 0;
        tam_input_pos = 0;
        strcpy(status_msg, "New TAM app");
        return;
    }
    
    if(key == '\b') {
        if(tam_input_pos > 0) {
            tam_input_pos--;
            tam_input[tam_input_pos] = 0;
        }
    } else if(key == '\n' || key == '\r') {
        if(tam_input_pos < 4090) {
            tam_input[tam_input_pos++] = '\n';
            tam_input[tam_input_pos] = 0;
        }
    } else if(key >= ' ' && key <= '~' && tam_input_pos < 4090) {
        tam_input[tam_input_pos++] = key;
        tam_input[tam_input_pos] = 0;
    }
}

void tam_parser_open(void) {
    tam_input[0] = 0;
    tam_input_pos = 0;
    strcpy(tam_filepath, "/user/myapp.tam");
    strcpy(status_msg, "TAM App Creator - Ready");
    
    // Load default template
    strcpy(tam_input, "#app MyApp\n#icon \"🛠️\"\n#window 600 400\n#draw\n    fill_rect 0,0,600,400 0x001A0A\n    text \"Hello from TAM!\" 20,40 0x00FF00\n#click\n    text \"Clicked!\" 20,80 0xFFFF00\n#key\n    if key='q' end\n");
    tam_input_pos = strlen(tam_input);
    
    gui_run_auto_app("🛠️ TAM App Creator", 60, 40, 640, 480, tam_draw, tam_click, tam_key);
}